spin_manifest_version = 2

[application]
authors = ["M.-Leander Reimer <mario-leander.reimer@qaware.de>"]
description = "Spin WASM application to serve the Chuck Norris Jokes API as caching proxy"
name = "spin-norris-jokes"
version = "0.2.0"

[[trigger.http]]
route = "/api/jokes/random"
component = "random"

[component.random]
source = "random/target/random.wasm"
exclude_files = ["random/**/node_modules"]
allowed_outbound_hosts = ["https://api.chucknorris.io"]
key_value_stores = ["jokes"]

[component.random.build]
command = "npm run build"
workdir = "random"
watch = ["src/*.ts", "package.json"]

[[trigger.http]]
route = "/api/jokes/categories"
component = "categories"

[component.categories]
source = "categories/target/categories.wasm"
exclude_files = ["categories/**/node_modules"]
allowed_outbound_hosts = ["https://api.chucknorris.io"]
key_value_stores = ["default"]

[component.categories.build]
command = "npm run build"
workdir = "categories"
watch = ["src/*.ts", "package.json"]

[[trigger.http]]
route = "/api/jokes/search"
component = "search"

[component.search]
source = "search/target/search.wasm"
exclude_files = ["search/**/node_modules"]
allowed_outbound_hosts = ["https://api.chucknorris.io"]
key_value_stores = ["jokes"]

[component.search.build]
command = "npm run build"
workdir = "search"
watch = ["src/*.ts", "package.json"]