name: Build with NodeJS and Spin

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup `spin`
      uses: fermyon/actions/spin/setup@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        plugins: cloud,js2wasm

    - name: Install NPM dependencies
      run: |
        task dependencies

    - name: Spin Build
      run: |
        spin build
